### ISSUE TITLE
Is LLVM still required?

### ISSUE THREAD

**Issue by jserv** [Kray-G/kilite#1]
While building this project, I encountered the following warnings:
```
CMake Warning at CMakeLists.txt:75 (find_package):
  By not providing "FindLLVM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LLVM", but
  CMake did not find one.

  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
```

I am not sure if LLVM is one of the necessary packages for kilite.

**Comment by Kray-G** [comment]
Sorry for the late reply, but thanks for trying this project.
I don't think we need LLVM. That's no problem the message is just a notification and you can ignore it.
It's okay that you can find the "mir_static.lib" and building executable will be also successful.

If you have any other trouble, don't hesitate to ask me, anytime.

**Comment by jserv** [comment]
Confirmed that recent changes eliminate the LLVM checks. Thanks!
